// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bnhjtwjlrrdvlrtrzbld.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJuaGp0d2pscnJkdmxydHJ6YmxkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MTgwMTUsImV4cCI6MjA2MTA5NDAxNX0.qyjqWI5PutZnNv9T58Yl9v8FVuSHbT8GRMzpLqUYua8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);